USE MASTER;
IF EXISTS (SELECT [name] FROM sys.databases WHERE [name] = 'BikelyDB' )
BEGIN
ALTER DATABASE BikelyDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE BikelyDB ;
END

CREATE DATABASE BikelyDB
GO

USE BikelyDB
GO